name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.2
    - uses: actions/cache@v4.0.2
      with:
        path: ~/.cargo
        key: shared
    - name: Build
      run: cargo build --release && ls -lh target/*
    - name: Build tests
      run: cargo build --tests --benches
    - name: Run tests
      run: cargo test --all-targets
